// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmj6kHYJQZRZlizb5dl5EPjsxiC3B_JkM',
    appId: '1:714050791300:web:adbbdd35b5a91baa2f5fd1',
    messagingSenderId: '714050791300',
    projectId: 'labs-22a6a',
    authDomain: 'labs-22a6a.firebaseapp.com',
    databaseURL: 'https://labs-22a6a-default-rtdb.firebaseio.com',
    storageBucket: 'labs-22a6a.appspot.com',
    measurementId: 'G-Q4SMRBMMJ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKUDqL0VLtwGLu3QoZQmb6fa6ns_5XMd0',
    appId: '1:714050791300:android:49ad6babf07c96f22f5fd1',
    messagingSenderId: '714050791300',
    projectId: 'labs-22a6a',
    databaseURL: 'https://labs-22a6a-default-rtdb.firebaseio.com',
    storageBucket: 'labs-22a6a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_v-VlJRhCT2Oy4PLYiH_i4IQfFFHVzl8',
    appId: '1:714050791300:ios:5b3826605c60ea5e2f5fd1',
    messagingSenderId: '714050791300',
    projectId: 'labs-22a6a',
    databaseURL: 'https://labs-22a6a-default-rtdb.firebaseio.com',
    storageBucket: 'labs-22a6a.appspot.com',
    iosClientId: '714050791300-6pd2jc6qtu2s69tbll1b7fe41p78uiit.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_v-VlJRhCT2Oy4PLYiH_i4IQfFFHVzl8',
    appId: '1:714050791300:ios:5b3826605c60ea5e2f5fd1',
    messagingSenderId: '714050791300',
    projectId: 'labs-22a6a',
    databaseURL: 'https://labs-22a6a-default-rtdb.firebaseio.com',
    storageBucket: 'labs-22a6a.appspot.com',
    iosClientId: '714050791300-6pd2jc6qtu2s69tbll1b7fe41p78uiit.apps.googleusercontent.com',
    iosBundleId: 'com.example.fintechApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB_i50K1H5ijRwFR6gzyJAZIhEr_CoLBUA',
    appId: '1:714050791300:web:ae8d9677181996c02f5fd1',
    messagingSenderId: '714050791300',
    projectId: 'labs-22a6a',
    authDomain: 'labs-22a6a.firebaseapp.com',
    databaseURL: 'https://labs-22a6a-default-rtdb.firebaseio.com',
    storageBucket: 'labs-22a6a.appspot.com',
    measurementId: 'G-MD2PB3Y96D',
  );
}
